config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name ,:presence=>true,length: { minimum: 30 ,minimum:1 }
  validates :author ,:presence=>true
  validates :rating ,:inclusion=>{in:[1,2,3,4,5],:message=>"Rate is from 1 to 5"}
  # validates :publish_year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book , only: [:show,:edit,:update,:destroy]
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book= Book.new
  end

  def edit
  end
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: "Book was successfully created." }
        format.json { render :index, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_path, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: "books was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def set_book
    @book = Book.find(params[:id])
  end
  def book_params
    params.require(:book).permit(:name ,:author, :description ,:publish_year,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="card">
  <div class="card-header">
    <center>Book Information</center>
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong>Name: </strong><%= book.name %></h5>
    <h5 class="card-title"><strong>Author: </strong><%= book.author %></h5>
    <h5 class="card-title"><strong>Description: </strong><%= book.description %></h5>
    <h5 class="card-title"><strong>Publish Year: </strong><%= book.publish_year %></h5>
    <h5 class="card-title"><strong>rating: </strong><%= book.rating %></h5>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: @book) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.text_field :name , placeholder:"Name Book" ,class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :author , placeholder:"Author Name" ,class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.text_area :description , placeholder:"Description" ,class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :publish_year.year , placeholder:"Publish Year" ,class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.number_field :rating , placeholder:"Rating" ,class:"form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Book edit</h1>
<%= render "form", book: @book %>

<%= link_to 'Back' ,books_path %>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<br>
<table class="table">
  <thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Description</th>
    <th>Publish Year</th>
    <th>Rating</th>
    <th colspan="3" style="text-align: center">Action</th>
  </tr>

  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.description %></td>
      <td><%= book.publish_year %></td>
      <td><%= book.rating %></td>
      <td><%= link_to 'show' ,book %></td>
      <td><%= link_to 'edit' ,edit_book_path(book) %></td>
<!--      <td><%#= link_to "delete",book, data: { "turbo-method": :delete }, class: "btn btn-danger ml-3" %></td>-->
      <td><%= button_to 'Destroy',book ,method: :delete ,class: "btn btn-danger ml-3" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Book' ,new_book_path %>

app/views/books/new.html.erb
<center> <b>Add new Book</b></center>
<br>
<%= render 'form' ,book: @books %>

<%= link_to 'Back' ,books_path %>

app/views/books/show.html.erb
<%= render 'book' ,book:@book %>

<div>
  <%= link_to "Edit this books", edit_book_path(@book) %> |
  <%= link_to "Back to Book", books_path %>
  <%= button_to "Destroy this books", @book, method: :delete, class: "btn btn-danger ml-3"%>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/books">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/books/new">Add Book <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EBooks</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<body>
<%= render 'layouts/header' %>
<div class="container ">
  <%= yield %>
</div>
</body>
</html>